spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
            url:
                read-write: jdbc:mysql://localhost:3306/ct?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
                read-only: jdbc:mysql://localhost:3306/ct?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
